config/routes.rb
Rails.application.routes.draw do

  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/home')
  get 'home/library'
  get 'donate', to: 'home#donate'
  get 'donation/:code', to: 'home#in_kind'
  post 'sponsor_classroom', to: 'home#sponsor_classroom'
  post 'sponsor_grade', to: 'home#sponsor_grade'
  get 'give', to: 'home#give'
  get 'bookdrive', to: redirect('https://www.bushhoustonliteracy.org/book-drive', status: 302)
  get 'search/:slug', to: redirect('/search?slug=%{slug}'), as: 'old_search'
  get 'wishlists', to: 'home#wishlists'
  post 'success', to: 'home#success'

  get  'login', to: 'home#login'
  get 'logout', to: 'home#logout'

  namespace :admin do
    root to: 'home#index'
    get 'reports', to: 'home#reports', as: 'reports_path'
    resources :languages do
      member do
        put 'is_disabled'
      end
    end
    resources :reading_levels do
      member do
        put 'is_disabled'
      end
    end
    resources :surveys do
      member do
        put 'is_disabled'
        post 'reorder'
      end
      resources :survey_questions
    end
    resources :users do
      member do
        put 'toggle_admin'
      end
    end
    resources :books
    resources :catalogs do
      member do
        get 'export'
        put 'active'
        post 'upload'
      end
      resources :catalog_entries
      resources :packs do
        member do
          post 'generate_packs'
        end
      end
    end
    resources :contents
    resources :organizations do
      member do
        put 'included'
      end
      resources :partners do
        member do
          put 'toggle_coordinator'
        end
      end
      resources :campaigns do
        member do
          get 'order_sheet'
          get 'pack_order_sheet'
          get 'pick_list'
          get 'distribution'
          get 'export'
          get 'book_count'
          get 'exportroster'
          get 'readers'
          get 'new_grade_sponsorship'
          post 'create_grade_sponsorship'
          get 'new_external_donation'
          post 'create_external_donation'
          put 'donations'
          put 'wishlists'
          get 'export_survey'
          get 'inventory'
        end
        resources :campaign_survey_configs
        resources :wishlists do
          member do
            get 'manage'
            put 'toggle_delivered'
            get 'take_survey'
            post 'save_response'
            get 'survey_complete'
          end
          collection do
            get  'edit_multiple'
            put  'update_multiple'
            delete 'destroy_multiple'
            get  'edit_upload'
            post 'upload'
            get  'download'
          end
          resources :wishlist_entries
          resources :appreciation_notes
        end
      end
    end
  end

  namespace :partner, :path => 'volunteer' do
    root to: 'home#index'
    resources :organizations do
      resources :partners
      resources :campaigns do
        member do
          get 'order_sheet'
          get 'get_order_sheet'
          get 'pick_list'
          get 'distribution'
          get 'export'
          get 'book_count'
          get 'exportroster'
          get 'readers'
          put 'donations'
          put 'wishlists'
          get 'inventory'
        end
        resources :wishlists do
          member do
            get 'manage'
            put 'toggle_delivered'
            get 'take_survey'
            post 'save_response'
            get 'survey_complete'
          end
          collection do
            get  'edit_multiple'
            put  'update_multiple'
            get  'edit_upload'
            post 'upload'
            get  'download'
          end
          resources :wishlist_entries
          resources :appreciation_notes
        end
      end
    end
  end

  # Default Scrivito routes. Adapt them to change the routing of CMS objects.
  # See the documentation of 'scrivito_route' for a detailed description.
  scrivito_route '/', using: 'homepage'
  scrivito_route '(/)(*slug-):id', using: 'slug_id'
  scrivito_route '/(*permalink)/(:slug)', using: 'permalink', format: false

  #work around to get search_url working...this route should not actually match
  #b/c scrivito above will catch it
  get 'search/(:slug)', to: redirect('/search?slug=%{slug}'), as: 'search'


end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :survey_questions, -> { order(sequence: :asc) }
end

app/controllers/admin/surveys_controller.rb
class Admin::SurveysController < Admin::BaseController
  def index
    @surveys = Survey.all
    respond_to do |format|
      format.html
      format.json { render json: @surveys }
    end
  end

  def show
    @survey = Survey.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @survey }
    end
  end

  def new
    @survey = Survey.new
    respond_to do |format|
      format.html { render 'common/form', locals: {form_title: 'New Survey', model: 'surveys'} }
      format.json { render json: @survey }
    end
  end

  def edit
    @survey = Survey.find(params[:id])
    respond_to do |format|
      format.html { render 'common/form', locals: {form_title: 'Edit Survey', model: 'surveys'}  }
      format.json { render json: @survey }
    end
  end

  def update
    @survey = Survey.find(params[:id])
    @survey.update!(survey_params)
    flash[:notice] = "Survey updated."
    @surveys = Survey.all
    respond_to do |format|
      format.html { render "index" }
      format.json { render json: @survey }
    end
  end

  def create
    @survey = Survey.create!(survey_params)
    flash[:success] = "Thank you! Your survey has been added."
    respond_to do |format|
      format.html { render "show" }
      format.json { render json: @survey }
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy()
    if @survey.errors.any?
      @survey.errors.full_messages.each do |message|
        flash[:warning] = message
      end
    end
    @surveys = Survey.all
    respond_to do |format|
      format.html { render "index" }
      format.json { render json: @surveys}
    end
  end

  def is_disabled
    @survey = Survey.find(params[:id])
    @survey.is_disabled = !@survey.is_disabled
    @survey.save
  end

  def reorder
    @survey = Survey.find(params[:id])
    params[:sorted].each_with_index do |id, idx|
      @survey.survey_questions.find(id.gsub(/\D+/, '').to_i).update(sequence: idx)
    end
    respond_to do |format|
      format.html { render "show" }
      format.js
      format.json { render json: @survey}
    end
  end

private
  def survey_params
    params.require(:survey).permit(:name, :description, :is_disabled)
  end
end

app/views/admin/surveys/_form.html.erb
<%= form_for [:admin, @survey], :html => {:class => "form-horizontal"} do |f| %>

  <div class="form-group">
    <%= f.label :name, class: "col-md-1 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "col-md-1 control-label" %>
    <div class="col-md-4">
      <%= f.text_area :description, class: "form-control", :rows => 6 %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-1 col-md-4">
      <div class="checkbox">
        <label>
          <%= f.check_box :is_disabled %>
          Disabled
        </label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-1 col-md-4">
      <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
      <%= link_to 'Back', admin_surveys_url, :class => "btn btn-default"%>
    </div>
  </div>

<% end %>

app/views/admin/surveys/_survey.html.erb
<tr>
  <td><%= link_to survey.name, [:admin, survey] %></td>
  <td><%= survey.description %></td>
  <td><%= check_box_tag 'is_disabled', survey.id, survey.is_disabled,
            data: {
              remote: true,
              url: is_disabled_admin_survey_url(survey),
              method: "PUT"
              } %></td>

  <td>
    <%= link_to "Edit", edit_admin_survey_url(survey), class: "btn btn-warning btn-xs" %>
    <%= link_to "Delete", admin_survey_url(survey),  method: :delete, class: "btn btn-danger btn-xs", data: {confirm: 'This action cannot be undone. Are you sure?'} %>
  </td>
</tr>

app/views/admin/surveys/index.html.erb
<div class="panel panel-default outer-panel panel-info">
  <!-- Default panel contents -->
  <div class="panel-heading"><h3 class="panel-title">Survey Management</h3></div>
  <div class="panel-body">
  </div>
  <div class="panel panel-default outer-panel">
    <!-- Default panel contents -->
    <div class="panel-heading"><h3 class="panel-title">Surveys</h3></div>
      <table class="table table-striped table-condensed">
        <caption><%= link_to '<i class="glyphicon glyphicon-plus"></i> New Survey'.html_safe, new_admin_survey_url, :class => "btn btn-xs btn-primary" %></caption>
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Disabled?</th>
            <th>&nbsp;</th>
          </tr>
        </thead>
        <tbody>
      <%= render :partial => 'survey', :collection => @surveys %>
        </tbody>
      </table>
    </div>
</div>

app/views/admin/surveys/reorder.js.erb
true

app/views/admin/surveys/show.html.erb
<div class="panel panel-default outer-panel panel-info">
  <!-- Default panel contents -->
  <div class="panel-heading"><h3 class="panel-title">Survey Detail</h3></div>
  <div class="panel-body">
    <dl class="dl-horizontal">
      <dt>Name</dt>
      <dd><%= @survey.name %></dd>
      <dt>Descripton</dt>
      <dd><%= @survey.description %></dd>
      <dt>Disabled?</dt>
      <dd><%= @survey.is_disabled %>
    </dl>
  </div>
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><h3 class="panel-title">Questions</h3></div>
    <table class="table table-striped table-condensed">
      <caption class="toggle-show">
        <%= link_to '<i class="glyphicon glyphicon-plus"></i> New Question'.html_safe, new_admin_survey_survey_question_url(@survey), :class => "btn btn-xs btn-primary", :remote => true %>
      </caption>
      <thead>
        <tr>
          <th>Question</th>
          <th>Description</th>
          <th>Type</th>
          <th class="toggle-show">&nbsp;</th>
        </tr>
      </thead>
      <tbody class="sortable">
    <%= render :partial => 'common/surveys/survey_question', :collection => @survey.survey_questions %>
      </tbody>
    </table>
  </div>
</div>
<% content_for :foot do %>
<script type="text/javascript">
$(function() {
  $('.sortable').sortable({update: function() {
    $.ajax({
        type: 'POST',
        url: '<%= params[:id] %>/reorder',
        dataType: 'json',
        contentType: 'application/json',
        data: JSON.stringify({
          sorted: $(this).sortable('toArray'),
        }),
      });
  }});
});
</script>
<% end %>