config/routes.rb
Rails.application.routes.draw do

  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/home')
  get 'home/library'
  get 'donate', to: 'home#donate'
  get 'donation/:code', to: 'home#in_kind'
  post 'sponsor_classroom', to: 'home#sponsor_classroom'
  post 'sponsor_grade', to: 'home#sponsor_grade'
  get 'give', to: 'home#give'
  get 'bookdrive', to: redirect('https://www.bushhoustonliteracy.org/book-drive', status: 302)
  get 'search/:slug', to: redirect('/search?slug=%{slug}'), as: 'old_search'
  get 'wishlists', to: 'home#wishlists'
  post 'success', to: 'home#success'

  get  'login', to: 'home#login'
  get 'logout', to: 'home#logout'

  namespace :admin do
    root to: 'home#index'
    get 'reports', to: 'home#reports', as: 'reports_path'
    resources :languages do
      member do
        put 'is_disabled'
      end
    end
    resources :reading_levels do
      member do
        put 'is_disabled'
      end
    end
    resources :surveys do
      member do
        put 'is_disabled'
        post 'reorder'
      end
      resources :survey_questions
    end
    resources :users do
      member do
        put 'toggle_admin'
      end
    end
    resources :books
    resources :catalogs do
      member do
        get 'export'
        put 'active'
        post 'upload'
      end
      resources :catalog_entries
      resources :packs do
        member do
          post 'generate_packs'
        end
      end
    end
    resources :contents
    resources :organizations do
      member do
        put 'included'
      end
      resources :partners do
        member do
          put 'toggle_coordinator'
        end
      end
      resources :campaigns do
        member do
          get 'order_sheet'
          get 'pack_order_sheet'
          get 'pick_list'
          get 'distribution'
          get 'export'
          get 'book_count'
          get 'exportroster'
          get 'readers'
          get 'new_grade_sponsorship'
          post 'create_grade_sponsorship'
          get 'new_external_donation'
          post 'create_external_donation'
          put 'donations'
          put 'wishlists'
          get 'export_survey'
          get 'inventory'
        end
        resources :campaign_survey_configs
        resources :wishlists do
          member do
            get 'manage'
            put 'toggle_delivered'
            get 'take_survey'
            post 'save_response'
            get 'survey_complete'
          end
          collection do
            get  'edit_multiple'
            put  'update_multiple'
            delete 'destroy_multiple'
            get  'edit_upload'
            post 'upload'
            get  'download'
          end
          resources :wishlist_entries
          resources :appreciation_notes
        end
      end
    end
  end

  namespace :partner, :path => 'volunteer' do
    root to: 'home#index'
    resources :organizations do
      resources :partners
      resources :campaigns do
        member do
          get 'order_sheet'
          get 'get_order_sheet'
          get 'pick_list'
          get 'distribution'
          get 'export'
          get 'book_count'
          get 'exportroster'
          get 'readers'
          put 'donations'
          put 'wishlists'
          get 'inventory'
        end
        resources :wishlists do
          member do
            get 'manage'
            put 'toggle_delivered'
            get 'take_survey'
            post 'save_response'
            get 'survey_complete'
          end
          collection do
            get  'edit_multiple'
            put  'update_multiple'
            get  'edit_upload'
            post 'upload'
            get  'download'
          end
          resources :wishlist_entries
          resources :appreciation_notes
        end
      end
    end
  end

  # Default Scrivito routes. Adapt them to change the routing of CMS objects.
  # See the documentation of 'scrivito_route' for a detailed description.
  scrivito_route '/', using: 'homepage'
  scrivito_route '(/)(*slug-):id', using: 'slug_id'
  scrivito_route '/(*permalink)/(:slug)', using: 'permalink', format: false

  #work around to get search_url working...this route should not actually match
  #b/c scrivito above will catch it
  get 'search/(:slug)', to: redirect('/search?slug=%{slug}'), as: 'search'


end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :organization
  has_many :wishlists, :dependent => :destroy
  has_many :campaign_catalogs, :dependent => :delete_all
  has_many :catalogs, through: :campaign_catalogs
  has_many :donations
  has_many :campaign_survey_configs
  belongs_to :prek_k_source, class_name: "Catalog", foreign_key: "prek_k_source_id", optional: true
  belongs_to :first_fifth_source, class_name: "Catalog", foreign_key: "first_fifth_source_id", optional: true

  validates :prek_k_source_id, presence: true, if: :use_packs?
  validates :first_fifth_source_id, presence: true, if: :use_packs?
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController
  def index
    redirect_to admin_organizations_path
  end

  def reports
    wishlist = Wishlist.joins(campaign: :organization)
    wishlist = wishlist.where("wishlists.created_at > ?", params[:startDate]) unless params[:startDate].blank?
    wishlist = wishlist.where("wishlists.created_at < ?", params[:endDate]) unless params[:endDate].blank?


    donation = Donation
    donation = donation.where("donations.created_at > ?", params[:startDate]) unless params[:startDate].blank?
    donation = donation.where("donations.created_at < ?", params[:endDate]) unless params[:endDate].blank?

    case params[:sponsorshipType]
      when 'Classroom'
        donation = donation.where(is_classroom_sponsorship: true)
      when 'Grade'
        donation = donation.where(is_grade_sponsorship: true)
    end

    # Doing this before adding the includedOrganizations param so that we can
    # show all potential campaingns and orgs in the UI
    campaigns = wishlist.includes(:campaign).collect{|w| w.campaign}.uniq.sort_by{|c| c.name}
    organizations = Organization.where("id in (?)", campaigns.collect{|c|c.organization_id}).order(:name)

    if params[:includedOrganizations]
      wishlist = wishlist.where("campaigns.organization_id in (?)", params[:includedOrganizations])
    end

    if params[:includedCampaigns]
      wishlist = wishlist.where("campaigns.id in (?)", params[:includedCampaigns])
    end

    # First get all Donations where no wishlist or campaign is set for the date range
    donations = {
      0 => donation.where("campaign_id is null and wishlist_id is null").sum(:amount)
    }

    # Next get all campaign specific donations
    d2 = donation.joins(campaign: :organization)
    if params[:includedOrganizations]
      d2 = d2.where("campaigns.organization_id in (?)", params[:includedOrganizations])
    end
    if params[:includedCampaigns]
      d2 = d2.where("campaign_id in (?)", params[:includedCampaigns])
    end
    donations.merge!(d2.group(:organization_id).sum(:amount))

    # Finally get all wishlist donations donations
    d3 = donation.joins(wishlist: {campaign: :organization})
    if params[:includedOrganizations]
      d3 = d3.where("campaigns.organization_id in (?)", params[:includedOrganizations])
    end
    if params[:includedCampaigns]
      d3 = d3.where("campaigns.id in (?)", params[:includedCampaigns])
    end
    donations.merge!(d3.group(:organization_id).sum(:amount))

    @data = {
      :wishlists => wishlist.group(:organization_id).count,
      :donations => donations,
      :sponsored_wishlists => wishlist.includes(:donations).where.not(donations: {id: nil}).group(:organization_id).count(),
      :campaigns => campaigns,
      :organizations => organizations
    }

    @data[:wishlists_total] = @data[:wishlists].inject(0){|sum, tuple| sum += tuple[1]}
    @data[:donations_total] = @data[:donations].inject(0){|sum, tuple| sum += tuple[1]}
    @data[:sponsored_wishlists_total] = @data[:sponsored_wishlists].inject(0){|sum, tuple| sum += tuple[1]}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include CommonSearchActions
  before_action :find_organization, only: [:search, :wishlists]
  before_action :find_wishlists, only: [:search, :wishlists]
  before_action :find_content, only: [:index, :search, :wishlists]

  def index
  end

  def give
  end

  def bookdrive
  end

  def login
    respond_to do |format|
      format.html
      format.json { render json: {:error => "No auth token sent"} }
    end
  end

  def logout
    reset_session
    redirect_to "https://#{Rails.application.config.auth0_endpoint}/v2/logout?returnTo=#{params['returnTo']}&client_id=#{params['client_id']}"
  end

  def library
  end

  def donate
    addl_donation = params[:addl_donation].nil? ? 0.0 : params[:addl_donation].to_d
    addl_donation_slug = params[:addl_donation_slug].nil? ? 0.0 : params[:addl_donation_slug].to_d
    @is_classroom_sponsored = params[:classroom] == 'true'
    @is_grade_sponsored = params[:grade] == 'true'
    if params[:id_list].nil?
      @wishlists = []
      @donationLevel = addl_donation + addl_donation_slug
      @schoolname = "None"
      @Campaign = "General"
      @reader_name = ""
      @wishListID = ""
      @slug = ""
      @campaign_id = ""
      if !params[:campaign_id].nil? && campaign = Campaign.find(params[:campaign_id])
        @Campaign = campaign.name
        @schoolname = campaign.organization.name
        @slug = campaign.organization.slug
        @campaign_id = campaign.id
      end
      if !params[:organization_id].nil? && org = Organization.find(params[:organization_id])
        @schoolname = org.name
        @slug = org.slug
      end
    else
      school = {}
      campaign = {}
      reader = {}
      slug = {}

      @wishlists = Wishlist.joins([{:campaign => :organization}]).where("wishlists.id in (?)", params[:id_list].split(",").map(&:to_i)).all
      @wishlists.each{|w|
        school[w.campaign.organization.name] = true
        campaign[w.campaign.name] = true
        reader[w.public_name] = true
        slug[w.campaign.organization.slug] = true
      }
      @schoolname = school.keys.join(",")
      @donationLevel = addl_donation + addl_donation_slug + (30.0*@wishlists.count) #TODO: Make the amount configurable
      @Campaign = campaign.keys.join(",")
      @reader_name = reader.keys.join(",")
      @wishListID = params[:id_list]
      @slug = slug.keys.join("") if slug.count == 1
      session[:wishlist_cart] = params[:id_list]
    end
  end

  def sponsor_classroom
    @wishlist_ids = Wishlist.joins('LEFT JOIN donations on donations.wishlist_id = wishlists.id').where("teacher = ? and wishlists.campaign_id = ? and donations.id is NULL", params[:teacher], params[:campaign_id]).pluck(:id)
  end

  def sponsor_grade
    @wishlist_ids = Wishlist.joins('LEFT JOIN donations on donations.wishlist_id = wishlists.id').where("grade = ? and wishlists.campaign_id = ? and donations.id is NULL", params[:grade], params[:campaign_id]).pluck(:id)
  end

  def search
  end

  def wishlists
    @is_classroom_sponsored = false
    @is_grade_sponsored = false
    respond_to do |format|
      format.js {}
    end
  end

  def in_kind
    @donations = Donation.where(confirmation_code: params[:code], is_in_kind: true)
  end

  def success
    @wishlists = Wishlist.joins([{:campaign => :organization}]).where("wishlists.id in (?)", params[:id_list].split(",").map(&:to_i)).all
    if @wishlists.count > 0
      amt = params[:amount].to_d/@wishlists.count unless params[:amount].nil? || @wishlists.count == 0
      @wishlists.each do |w|
        @donation = w.donations.create!({:confirmation_code => params[:confirmation_code], 
          :amount => amt, 
          :is_classroom_sponsorship => params[:is_classroom_sponsored],
          :is_grade_sponsorship => params[:is_grade_sponsored],
          :is_in_kind => params[:is_in_kind],
          :in_name_of => params[:in_name_of],
          :in_kind_message => params[:in_kind_message]})
      end
    elsif campaign = Campaign.find_by_id(params[:campaign_id])
      @donation = campaign.donations.create!({:confirmation_code => params[:confirmation_code], 
        :amount => params[:amount],
        :is_in_kind => params[:is_in_kind],
        :in_name_of => params[:in_name_of],
        :in_kind_message => params[:in_kind_message]})
    else
      @donation = Donation.create!({:confirmation_code => params[:confirmation_code], 
        :amount => params[:amount],
        :is_in_kind => params[:is_in_kind],
        :in_name_of => params[:in_name_of],
        :in_kind_message => params[:in_kind_message]})
    end

    session[:wishlist_cart] = nil

    respond_to do |format|
      format.html { render "index" }
      format.json { render json: @donation }
    end
  end

private

  def find_organization
    unless params[:slug].nil?
      @organization = Organization.find_by_slug(params[:slug])
    end

    #if !params[:term].nil? && @organization.nil?
    #  @organization = Organization.find_by_name(params[:term])
    #end
  end

  def find_content
    @content = Content.where(action_name: action_name).all.map{|c| [c.name, c.content]}.to_h
  end

end

app/controllers/partner/home_controller.rb
class Partner::HomeController < Partner::BaseController
  before_action :find_organizations
  def index
    if get_role == 'coordinator'
      redirect_to partner_organizations_url
    else
    	@campaigns = Campaign.where(:organization => @organizations).all
      respond_to do |format|
        format.html
        format.json { render json: @campaigns }
      end
    end
  end

end

app/views/home/_search_results.html.erb
<% wishlists.in_groups_of(6, false) do |chunk| -%>
<div class="row wishlist-flex">
  <%= render partial: 'home/wishlist', collection: chunk %>
</div>
<% end -%>

app/views/home/_wishlist.html.erb
<%
  unique_id = 1 + rand(10000)
  has_price = !@wishlist_prices[wishlist.id].nil?
  has_donation = !@donations[wishlist.id].nil?
  funded = has_price && has_donation && @wishlist_prices[wishlist.id] <= @donations[wishlist.id]
  already_sponsored = @classroom_sponsored.include?(wishlist.id)
%>
<div class="search-entry" data-wishlist-id=<%= wishlist.id %>>
  <div>
    <div class="search-entry-header">
      <h3><%= wishlist.public_name %>
        <% if wishlist.reader_age %>
         - Age <%= wishlist.reader_age %>
         <% end %></h3>
      <h4>Grade - <%= wishlist.grade %></h4>
      <h4 class="text-muted"><%= wishlist.campaign.organization.name %></h4>
      <h4 class="text-muted">Teacher: <%= wishlist.teacher %></h4>
      <%= button_to 'Sponsor Classroom', sponsor_classroom_url(:teacher => wishlist.teacher, :campaign_id => wishlist.campaign.id), remote: true, :class => 'btn btn-primary btn-notsponsored-class' unless already_sponsored %>
	    <%= button_to 'Sponsor Grade', sponsor_grade_url(:grade => wishlist.grade, :campaign_id => wishlist.campaign.id), remote: true, :class => 'btn btn-primary btn-notsponsored-class' unless already_sponsored %>
    </div>
    <div class="visible-xs" id="wishlist-book-list-toggle">
      <button class="btn btn-default btn-xs" data-toggle="collapse" data-target="#book-list-<%= unique_id%>" aria-expanded="false" aria-controls="book-list-<%= unique_id%>">
        Show Books
      </button>
    </div>
    <div class="list-group wishlist-book-list collapse" id="book-list-<%= unique_id%>">

      <%= render partial: 'home/wishlist_entry', collection: wishlist.wishlist_entries %>
    </div>
    <p><%= link_to 'Sponsor This Child', donate_url({:id_list => wishlist.id}), :class => 'btn btn-primary btn-notsponsored' if !funded %>
       <%= link_to 'Sponsored', '#', :class => 'btn btn-default disabled btn-sponsored', :disabled => true if funded %></p>
  </div>
</div>

app/views/home/_wishlist_entry.html.erb
<div class="list-group-item book-entry">
  <div id="book-cover"><img src="<%= wishlist_entry.catalog_entry.book.cover_image_url.html_safe %>" /></div>
  <div id="book-title"><%= wishlist_entry.catalog_entry.book.title.html_safe %></div>
</div>

app/views/home/bookdrive.html.erb
<div class="container-fluid">
  <div class="row bg-image-home">
    <%= render 'common/navbar' %>
    <div class="page-headline">
      <h1>INSPIRING READERS BY PROVIDING HOME LIBRARIES TO CHILDREN IN NEED</h1>
      <h3>An initiative of the Barbara Bush Houston Literacy Foundation</h3>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-3">
      <script src="https://widgets.kimbia.com/widgets/form.js?channel=barbarabushhoustonliteracyfoundation/ladies-bookdrive"></script>
    </div>
  </div>
</div>

app/views/home/catalog.html.erb
<div id="react-root"></div>
<script>
  var current_wishlist = null;
  var api_add_url;
  var api_delete_url;
  var back_url;
  var reader ;
  var grl = '';
  var book_limit;
  var all_active_books = [
    <% @active_books.each_with_index do |entry,idx| %>
    <%= ', ' unless idx == 0 %>{
      catalog_entry_id: <%= entry.id %>,
      name: '<%= j entry.book.title.html_safe %>',
      subname: '',
      imageUrl: '<%= entry.book.cover_image_url %>',
      author: '<%= j entry.book.author.html_safe %>',
      description: '<%= j entry.book.description.html_safe %>',
      level: '<%= j entry.book.level %>',
      ar_points: '<%= entry.book.ar_points %>',
      grl: '<%= entry.book.grl %>',
      dra: '<%= entry.book.dra %>',
      is_bilingual: <%= entry.book.is_bilingual %>,
      is_chapter: <%= entry.book.is_chapter %>
    }
    <% end %>
  ];

</script>
<%= javascript_include_tag 'main' %>

app/views/home/donate.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.11';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script>window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };

  return t;
}(document, "script", "twitter-wjs"));</script>
 <script>
var Campaign = "<%= @Campaign %>"; //Campaign name
var SchoolName = "<%= @schoolname %>"; //Organization name
var WishlistID = "<%= @wishListID %>"; // org wishlist ID
var DonationLevel = <%= @donationLevel %>; // org donationlevel
var ReaderName = "<%= @reader_name %>"; // reader name
var CampaignId = "<%= @campaign_id %>"; // campaign id
var is_classroom_sponsored = <%= @is_classroom_sponsored %>;
var is_grade_sponsored = <%= @is_grade_sponsored %>;

function kimbiaSuccess(kimbiaResponse) {
  var initCharge = kimbiaResponse.initialCharge.replace("$", "");
  var confCode = kimbiaResponse.confirmationCode;
  var wishlistId = getValueByLabel(kimbiaResponse.answers[0], 'Wishlist ID');
  var is_in_kind = $('#chk-in-kind').is(':checked');
  $('.k_footer,.k_navigationSpan,.back-wishlist-btn').hide();
  $('.share-btn-box').removeClass('share-btn-box-hide').addClass('share-btn-box-show');
  $.ajax({
    url: '<%= success_url %>',
    dataType: 'json',
    method: 'POST',
    data: {'id_list': wishlistId,
    'amount': initCharge,
    'confirmation_code': confCode,
    'campaign_id': CampaignId,
    'is_classroom_sponsored': is_classroom_sponsored,
    'is_grade_sponsored': is_grade_sponsored,
    'is_in_kind': is_in_kind,
    'in_name_of': $('#in-name-of').val(),
    'in_kind_message': $('#in-kind-message').val()
    },
    success: function(data) {
      if (is_in_kind) {
        $('#in-kind-link-container').toggleClass('hidden');
        var href = $('#in-kind-link').attr('href');
        href += confCode;
        $('#in-kind-link').attr('href', href);
        $('#in-kind-link').html(href);
      }
    }
  });
}
//Helper function from Widget_DataObject_JS.pdf
function getValueByLabel(aSignup, labelText, sublabelText){
  for(var a = 0; a < aSignup.length; a++){
    var formAnswerObject = aSignup[a];
    if(formAnswerObject.questionLabel === labelText){
      if(sublabelText == null || sublabelText == '' || formAnswerObject.questionSubLabel == sublabelText) {
        return formAnswerObject.data;
      }
    }
  }
  // found none
  return '';
}

function showPayment() {
  $("input[name=DonationLevel_FEE]").focus();
  $("input[name=DonationLevel_FEE]").blur();
  $("input[name=DonationLevel_FEE]").prop("disabled", true);
}

function kimbiaSubmit(f) {
  $(f.view.theForm.getElementsByTagName('button')[0]).hide();
  $(f.view.theForm.getElementsByTagName('button')[0]).after($('<span id="spinner">Submitting...</span>'));
  $('#in-kind-container').hide();
}

function kimbiaResponse(f) {
  $(f.view.theForm.getElementsByTagName('button')[0]).show();
  $(f.view.theForm.getElementsByTagName('button')[0]).find('#spinner').remove();
}

</script>
<div class="container-fluid">
  <div class="row bg-image-donate">
    <%= render 'common/navbar' %>
  </div>
</div>

<div class="container">
  <p>&nbsp;</p>
  <p class="back-wishlist-btn">
    <%= link_to 'Wish Lists', search_url(@slug), class: 'btn btn-primary btn-lg' %> Back to wish list search
  </p>

  <div class="panel panel-default" id="in-kind-container">
    <div class="panel-body">
      <h4>Donate in honor of option. <small>(limit 1 honoree per donation)</small></h4>
      <div class="checkbox form-group">
        <label>
          <input type="checkbox" id="chk-in-kind"> Make this donation in honor of someone
        </label>
      </div>
      <div class="form-group hidden in-kind">
        <label for="in-name-of">Honoree Name</label>
        <input type="text" class="form-control" id="in-name-of" placeholder="Name">
      </div>
      <div class="form-group hidden in-kind">
        <label for="in-kind-message">Special Message</label>
        <textarea class="form-control" rows="3" id="in-kind-message" maxlength="255"></textarea>
      </div>
      <p>Upon checkout, a certificate with the honoree’s name and your special message will open on a new page that you can print and mail. </p>
    </div>
  </div>




<!-- script to populate form tag -->
<% if ENV['IS_PRODUCTION'] %>
<script src="https://widgets.kimbia.com/widgets/form.js?channel=barbarabushhoustonliteracyfoundation/bbhlvirtualbookdrive&onshow=showPayment&oncomplete=kimbiaSuccess&onbeforesubmit=kimbiaSubmit&onplatformresponse=kimbiaResponse"></script>
<% else %>
<script src='https://widgets.kimbia.com/widgets/form.js?channel=barbarabushhoustonliteracyfoundation/bbhlvirtualbookdrivetest&onshow=showPayment&oncomplete=kimbiaSuccess&onbeforesubmit=kimbiaSubmit&onplatformresponse=kimbiaResponse'></script>
<% end %>
  <div class="share-btn-box share-btn-box-hide">
    <div class="panel panel-default hidden" id="in-kind-link-container">
      <div class="panel-body">
        <h4>In Honor of Certificate Link</h4>
        <p>Your in honor of donation link is: <a target="_blank" id="in-kind-link" href="<%= request.protocol + request.host_with_port %>/donation/"><%= request.protocol + request.host_with_port %>/donation/</a>
        </p>
      </div>
    </div>
    <p>Help spread the word about My Home Library and connect others to more children in need by sharing below</p>
    <div class="share-btn">
      <div class="fb-share-button" data-href="<%= search_url(@slug) %>"
        data-layout="button"
        data-size="large"
        data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank"
        href="https://www.facebook.com/sharer/sharer.php?u=<%= search_url(@slug).to_param %>&amp;src=sdkpreparse">Share</a></div>
    </div>
    <div class="share-btn">
      <a class="twitter-share-button"
      href="https://twitter.com/intent/tweet?text=Join%20me%20in%20sponsoring%20a%20home%20library%20for%20a%20child%20in%20need%20at&url=<%= search_url(@slug).to_param %>"
      data-size="large">
    Tweet</a>
    </div>
  </div>
</div>

<script>
$('#chk-in-kind').on('change', function(){
  $('.in-kind').toggleClass('hidden');
});
</script>

app/views/home/give.html.erb
<div class="container-fluid">
  <div class="row bg-image-home">
    <%= render 'common/navbar' %>
    <div class="page-headline">
      <h1>INSPIRING READERS BY PROVIDING HOME LIBRARIES TO CHILDREN IN NEED</h1>
      <h3>An initiative of the Barbara Bush Houston Literacy Foundation</h3>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-3">
      <script src="https://widgets.kimbia.com/widgets/form.js?channel=barbarabushhoustonliteracyfoundation/myhomelibrary-corporategiving"></script>
    </div>
  </div>
</div>

app/views/home/in_kind.html.erb
<style>
    @page {
        margin: 0.5in;
    }
    @media print {
        body {
            width: 7.5in;
            height: 10in;
        }
    }
</style>
<div id="in-kind-display">
    <%= image_tag 'kids_bg_4.jpg', id: 'bg-image' %>
    <div>
    <% unless @donations.size == 0
    # how many wishlists did the donation get split over
    donation_count = @donations.size
    kids = @donations.collect{|d| d.wishlist.try(:public_name)}.reject{|i| i.blank? }
    # how many wishlists potentially filled by all donation
    potential = (@donations.sum(:amount).to_f/30.0).ceil %>


        <h3><%= @donations.first.in_name_of %>,</h3>
        <p>A donation of <%= number_to_currency(@donations.sum(:amount)) %> was made in your name to the <strong>My Home Library</strong> program.
        This donation provides home libraries for <%= kids.size > 0 ? kids.to_sentence : pluralize([donation_count, potential].max, 'kid') %>  in the Houston area.
        </p>
        <blockquote><%= @donations.first.in_kind_message %></blockquote>
        <p>
    <% else %>
        <h2 class="text-center">No donation found</h2>
    <% end %>
        <h3>What is My Home Library?</h3>
        <p id="mhl-desc"><%= image_tag 'my-home-library.png', class: "mhl-logo", align: 'right' %>
        My Home Library is a literacy program across Houston schools hosted by the Barbara Bush Houston Literacy
        Foundation. Through My Home Library, community members are able to sponsor a home library for an economically
        disadvantaged child. If you’d like to also sponsor a child’s home library wish list, please go to <a href="https://www.myhomelibraryhouston.org">www.myhomelibraryhouston.org</a>.
        </p>
    </div>
</div>

app/views/home/library.html.erb
<div id="react-root" style="padding-top:60px"></div>
<script src="/assets/javascripts/main.js" /></script>

app/views/home/login.html.erb
<div class="row">
  <div class="col-md-2 col-md-offset-5">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Login Needed</h3>
      </div>
      <div class="panel-body">
        This area is for authorized users only. Please login to proceed.
        <%= link_to 'Login', 'auth/auth0', method: :post, class: 'btn btn-warning' %>
      </div>
    </div>
  </div>
</div>