config/routes.rb
Rails.application.routes.draw do

  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/home')
  get 'home/library'
  get 'donate', to: 'home#donate'
  get 'donation/:code', to: 'home#in_kind'
  post 'sponsor_classroom', to: 'home#sponsor_classroom'
  post 'sponsor_grade', to: 'home#sponsor_grade'
  get 'give', to: 'home#give'
  get 'bookdrive', to: redirect('https://www.bushhoustonliteracy.org/book-drive', status: 302)
  get 'search/:slug', to: redirect('/search?slug=%{slug}'), as: 'old_search'
  get 'wishlists', to: 'home#wishlists'
  post 'success', to: 'home#success'

  get  'login', to: 'home#login'
  get 'logout', to: 'home#logout'

  namespace :admin do
    root to: 'home#index'
    get 'reports', to: 'home#reports', as: 'reports_path'
    resources :languages do
      member do
        put 'is_disabled'
      end
    end
    resources :reading_levels do
      member do
        put 'is_disabled'
      end
    end
    resources :surveys do
      member do
        put 'is_disabled'
        post 'reorder'
      end
      resources :survey_questions
    end
    resources :users do
      member do
        put 'toggle_admin'
      end
    end
    resources :books
    resources :catalogs do
      member do
        get 'export'
        put 'active'
        post 'upload'
      end
      resources :catalog_entries
      resources :packs do
        member do
          post 'generate_packs'
        end
      end
    end
    resources :contents
    resources :organizations do
      member do
        put 'included'
      end
      resources :partners do
        member do
          put 'toggle_coordinator'
        end
      end
      resources :campaigns do
        member do
          get 'order_sheet'
          get 'pack_order_sheet'
          get 'pick_list'
          get 'distribution'
          get 'export'
          get 'book_count'
          get 'exportroster'
          get 'readers'
          get 'new_grade_sponsorship'
          post 'create_grade_sponsorship'
          get 'new_external_donation'
          post 'create_external_donation'
          put 'donations'
          put 'wishlists'
          get 'export_survey'
          get 'inventory'
        end
        resources :campaign_survey_configs
        resources :wishlists do
          member do
            get 'manage'
            put 'toggle_delivered'
            get 'take_survey'
            post 'save_response'
            get 'survey_complete'
          end
          collection do
            get  'edit_multiple'
            put  'update_multiple'
            delete 'destroy_multiple'
            get  'edit_upload'
            post 'upload'
            get  'download'
          end
          resources :wishlist_entries
          resources :appreciation_notes
        end
      end
    end
  end

  namespace :partner, :path => 'volunteer' do
    root to: 'home#index'
    resources :organizations do
      resources :partners
      resources :campaigns do
        member do
          get 'order_sheet'
          get 'get_order_sheet'
          get 'pick_list'
          get 'distribution'
          get 'export'
          get 'book_count'
          get 'exportroster'
          get 'readers'
          put 'donations'
          put 'wishlists'
          get 'inventory'
        end
        resources :wishlists do
          member do
            get 'manage'
            put 'toggle_delivered'
            get 'take_survey'
            post 'save_response'
            get 'survey_complete'
          end
          collection do
            get  'edit_multiple'
            put  'update_multiple'
            get  'edit_upload'
            post 'upload'
            get  'download'
          end
          resources :wishlist_entries
          resources :appreciation_notes
        end
      end
    end
  end

  # Default Scrivito routes. Adapt them to change the routing of CMS objects.
  # See the documentation of 'scrivito_route' for a detailed description.
  scrivito_route '/', using: 'homepage'
  scrivito_route '(/)(*slug-):id', using: 'slug_id'
  scrivito_route '/(*permalink)/(:slug)', using: 'permalink', format: false

  #work around to get search_url working...this route should not actually match
  #b/c scrivito above will catch it
  get 'search/(:slug)', to: redirect('/search?slug=%{slug}'), as: 'search'


end

app/models/reading_level.rb
class ReadingLevel < ApplicationRecord
end

app/controllers/admin/reading_levels_controller.rb
class Admin::ReadingLevelsController < Admin::BaseController
  def index
    @reading_levels = ReadingLevel.all
    respond_to do |format|
      format.html
      format.json { render json: @reading_levels }
    end
  end

  def show
    @reading_level = ReadingLevel.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @reading_level }
    end
  end

  def new
    @reading_level = ReadingLevel.new
    respond_to do |format|
      format.html { render 'common/form', locals: {form_title: 'New ReadingLevel', model: 'reading_levels'} }
      format.json { render json: @reading_level }
    end
  end

  def edit
    @reading_level = ReadingLevel.find(params[:id])
    respond_to do |format|
      format.html { render 'common/form', locals: {form_title: 'Edit ReadingLevel', model: 'reading_levels'}  }
      format.json { render json: @reading_level }
    end
  end

  def update
    @reading_level = ReadingLevel.find(params[:id])
    @reading_level.update!(reading_level_params)
    flash[:notice] = "ReadingLevel updated."
    @reading_levels = ReadingLevel.all
    respond_to do |format|
      format.html { render "index" }
      format.json { render json: @reading_level }
    end
  end

  def create
    @reading_level = ReadingLevel.create!(reading_level_params)
    flash[:success] = "Thank you! Your reading_level has been added."
    respond_to do |format|
      format.html { render "show" }
      format.json { render json: @reading_level }
    end
  end

  def destroy
    @reading_level = ReadingLevel.find(params[:id])
    @reading_level.destroy()
    if @reading_level.errors.any?
      @reading_level.errors.full_messages.each do |message|
        flash[:warning] = message
      end
    end
    @reading_levels = ReadingLevel.all
    respond_to do |format|
      format.html { render "index" }
      format.json { render json: @reading_levels}
    end
  end

  def is_disabled
    @reading_level = ReadingLevel.find(params[:id])
    @reading_level.is_disabled = !@reading_level.is_disabled
    @reading_level.save
  end

private
  def reading_level_params
    params.require(:reading_level).permit(:name, :is_disabled)
  end
end

app/views/admin/reading_levels/_form.html.erb
<%= form_for [:admin, @reading_level], :html => {:class => "form-horizontal"} do |f| %>

  <div class="form-group">
    <%= f.label :name, class: "col-md-1 control-label" %>
    <div class="col-md-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-1 col-md-4">
      <div class="checkbox">
        <label>
          <%= f.check_box :is_disabled %>
          Disabled
        </label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-1 col-md-4">
      <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
      <%= link_to 'Back', admin_reading_levels_url, :class => "btn btn-default"%>
    </div>
  </div>

<% end %>

app/views/admin/reading_levels/_reading_level.html.erb
<tr>
  <td><%= link_to reading_level.name, [:admin, reading_level] %></td>
  <td><%= check_box_tag 'is_disabled', reading_level.id, reading_level.is_disabled,
            data: {
              remote: true,
              url: is_disabled_admin_reading_level_url(reading_level),
              method: "PUT"
              } %></td>

  <td>
    <%= link_to "Edit", edit_admin_reading_level_url(reading_level), class: "btn btn-warning btn-xs" %>
  </td>
</tr>

app/views/admin/reading_levels/index.html.erb
<div class="panel panel-default outer-panel panel-info">
  <!-- Default panel contents -->
  <div class="panel-heading"><h3 class="panel-title">Reading Level Management</h3></div>
  <div class="panel-body">
  </div>
  <div class="panel panel-default outer-panel">
    <!-- Default panel contents -->
    <div class="panel-heading"><h3 class="panel-title">Reading Levels</h3></div>
      <table class="table table-striped table-condensed">
        <caption><%= link_to '<i class="glyphicon glyphicon-plus"></i> New Reading Level'.html_safe, new_admin_reading_level_url, :class => "btn btn-xs btn-primary" %></caption>
        <thead>
          <tr>
            <th>Name</th>
            <th>Disabled?</th>
            <th>&nbsp;</th>
          </tr>
        </thead>
        <tbody>
      <%= render :partial => 'reading_level', :collection => @reading_levels %>
        </tbody>
      </table>
    </div>
</div>

app/views/admin/reading_levels/show.html.erb
<div class="panel panel-default outer-panel panel-info">
  <!-- Default panel contents -->
  <div class="panel-heading"><h3 class="panel-title">Reading Level Detail</h3></div>
  <div class="panel-body">
    <dl class="dl-horizontal">
      <dt>Name</dt>
      <dd><%= @reading_level.name %></dd>
      <dt>Disabled?</dt>
      <dd><%= @reading_level.is_disabled %>
    </dl>
  </div>
</div>